### ISSUE TITLE
Sorting by Level weirdness

### ISSUE THREAD

**Issue by royaltivity** [maxiride/pf2e-encounters#30]
Since early levels are single digit, sorting by level creates an awkward assortment where levels 10 through 19 appear between levels 1 and 2, and level 20+ appear between 2 and 3. Making all levels 2 digits (-01, 00, 01, etc) might fix that, but I don't know how the data is generated, and thus have no idea how feasible that would be considering the breadth of the full bestiary.

**Comment by maxiride** [comment]
Yep I am ware of it and it is a bug referenced here #19
The issue **was** that the level was outputted as a string instead of an integer, the issue has been resolved in the generator and the new data has been pushed to the gh-pages branch (where the website is built upon).

You can indeed see that the new data source has levels as integers [here](https://raw.githubusercontent.com/maxiride/pf2e-encounters/gh-pages/creatures.json), however, for some reason the website hasn't been updated. It's like if the gh-pages update didn't fire upon the commit.

**Comment by EdNeedsBread** [comment]
Seems like the sorting issue is still here (or has returned)! It's odd though considering the JSON files of creatures seem to be have their levels set as integers and not strings.
